import {FOOD_CATEGORIES, TABLE_STATUS, ORDER_STATUS} from "./appConstants";
import {createReservationTime} from "../lib/helpers";

// prefill tables page if no data is found
export const SAMPLE_ORDERS = {
  table1: [
    {
      id: 1,
      title: "Classic Margherita Pizza",
      price: 15.99,
      quantity: 2,
      category: FOOD_CATEGORIES.MAIN_COURSE,
      image: "https://cdn.dummyjson.com/recipe-images/1.webp",
    },
    {
      id: 2,
      title: "Vegetarian Stir-Fry",
      price: 14.99,
      quantity: 1,
      category: FOOD_CATEGORIES.MAIN_COURSE,
      image: "https://cdn.dummyjson.com/recipe-images/2.webp",
    },
  ],
  table2: [
    {
      id: 6,
      title: "Quinoa Salad with Avocado",
      price: 12.99,
      quantity: 1,
      category: FOOD_CATEGORIES.APPETIZER,
      image: "https://cdn.dummyjson.com/recipe-images/6.webp",
    },
    {
      id: 7,
      title: "Tomato Basil Bruschetta",
      price: 9.99,
      quantity: 2,
      category: FOOD_CATEGORIES.APPETIZER,
      image: "https://cdn.dummyjson.com/recipe-images/7.webp",
    },
    {
      id: 3,
      title: "Chocolate Chip Cookies",
      price: 6.99,
      quantity: 1,
      category: FOOD_CATEGORIES.DESSERT,
      image: "https://cdn.dummyjson.com/recipe-images/3.webp",
    },
  ],
  table3: [
    {
      id: 5,
      title: "Mango Sticky Rice",
      price: 11.99,
      quantity: 1,
      category: FOOD_CATEGORIES.DESSERT,
      image: "https://cdn.dummyjson.com/recipe-images/5.webp",
    },
    {
      id: 10,
      title: "Caprese Salad",
      price: 10.99,
      quantity: 1,
      category: FOOD_CATEGORIES.APPETIZER,
      image: "https://cdn.dummyjson.com/recipe-images/10.webp",
    },
  ],
  table6: [
    {
      id: 11,
      title: "Chicken Biryani",
      price: 18.99,
      quantity: 2,
      category: FOOD_CATEGORIES.MAIN_COURSE,
      image: "https://cdn.dummyjson.com/recipe-images/11.webp",
    },
    {
      id: 4,
      title: "Chicken Alfredo Pasta",
      price: 16.99,
      quantity: 1,
      category: FOOD_CATEGORIES.MAIN_COURSE,
      image: "https://cdn.dummyjson.com/recipe-images/4.webp",
    },
  ],
  table7: [
    {
      id: 12,
      title: "Beef Tacos",
      price: 14.99,
      quantity: 3,
      category: FOOD_CATEGORIES.MAIN_COURSE,
      image: "https://cdn.dummyjson.com/recipe-images/12.webp",
    },
    {
      id: 8,
      title: "Chicken Caesar Salad",
      price: 13.99,
      quantity: 1,
      category: FOOD_CATEGORIES.MAIN_COURSE,
      image: "https://cdn.dummyjson.com/recipe-images/8.webp",
    },
  ],
};

export const getDefaultTables = () => [
  {
    id: "1",
    number: "1",
    status: TABLE_STATUS.OCCUPIED,
    orders: SAMPLE_ORDERS.table1,
    orderStatus: ORDER_STATUS.PREPARING,
    orderTime: createReservationTime(-1),
    reservedTime: null,
  },
  {
    id: "2",
    number: "2",
    status: TABLE_STATUS.OCCUPIED,
    orders: SAMPLE_ORDERS.table2,
    orderStatus: ORDER_STATUS.PENDING,
    orderTime: createReservationTime(0),
    reservedTime: null,
  },
  {
    id: "3",
    number: "3",
    status: TABLE_STATUS.OCCUPIED,
    orders: SAMPLE_ORDERS.table3,
    orderStatus: ORDER_STATUS.READY,
    orderTime: createReservationTime(-2),
    reservedTime: null,
  },
  {
    id: "4",
    number: "4",
    status: TABLE_STATUS.FREE,
    orders: [],
    orderStatus: null,
    orderTime: null,
    reservedTime: null,
  },
  {
    id: "5",
    number: "5",
    status: TABLE_STATUS.FREE,
    orders: [],
    orderStatus: null,
    orderTime: null,
    reservedTime: null,
  },
  {
    id: "A2",
    number: "A2",
    status: TABLE_STATUS.FREE,
    orders: [],
    orderStatus: null,
    orderTime: null,
    reservedTime: null,
  },
  {
    id: "6",
    number: "6",
    status: TABLE_STATUS.OCCUPIED,
    orders: SAMPLE_ORDERS.table6,
    orderStatus: ORDER_STATUS.DELIVERED,
    orderTime: createReservationTime(-3),
    reservedTime: null,
  },
  {
    id: "7",
    number: "7",
    status: TABLE_STATUS.OCCUPIED,
    orders: SAMPLE_ORDERS.table7,
    orderStatus: ORDER_STATUS.PREPARING,
    orderTime: createReservationTime(-1),
    reservedTime: null,
  },
  {
    id: "8",
    number: "8",
    status: TABLE_STATUS.FREE,
    orders: [],
    orderStatus: null,
    orderTime: null,
    reservedTime: null,
  },
  {
    id: "9",
    number: "9",
    status: TABLE_STATUS.FREE,
    orders: [],
    orderStatus: null,
    orderTime: null,
    reservedTime: null,
  },
  {
    id: "10",
    number: "10",
    status: TABLE_STATUS.FREE,
    orders: [],
    orderStatus: null,
    orderTime: null,
    reservedTime: null,
  },
  {
    id: "11",
    number: "11",
    status: TABLE_STATUS.RESERVED,
    orders: [],
    orderStatus: null,
    orderTime: null,
    reservedTime: createReservationTime(1),
  },
  {
    id: "12",
    number: "12",
    status: TABLE_STATUS.RESERVED,
    orders: [],
    orderStatus: null,
    orderTime: null,
    reservedTime: createReservationTime(1),
  },
  {
    id: "13",
    number: "13",
    status: TABLE_STATUS.FREE,
    orders: [],
    orderStatus: null,
    orderTime: null,
    reservedTime: null,
  },
  {
    id: "14",
    number: "14",
    status: TABLE_STATUS.FREE,
    orders: [],
    orderStatus: null,
    orderTime: null,
    reservedTime: null,
  },
  {
    id: "15",
    number: "15",
    status: TABLE_STATUS.FREE,
    orders: [],
    orderStatus: null,
    orderTime: null,
    reservedTime: null,
  },
  {
    id: "A1",
    number: "A1",
    status: TABLE_STATUS.RESERVED,
    orders: [],
    orderStatus: null,
    orderTime: null,
    reservedTime: createReservationTime(4),
  },
];
